# Generated by Django 4.2.9 on 2024-01-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organizer_alter_customuser_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizer",
            options={"verbose_name_plural": "Organizers"},
        ),
    ]
