# Generated by Django 5.0.1 on 2024-01-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizer_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name_plural': 'Organizers'},
        ),
    ]
